# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: ["maintenance", "ignore-for-release"]
    assignees: ["tsalo"]
    schedule:
      interval: "monthly"
